// ==========================================
// 🌍 GLOBAL STATE & CONFIGURATION
// ==========================================

// --- PeerJS & Networking Globals ---
window.peer = null;
window.conn = null;
window.connections = [];
window.myId = null;
window.role = null;

// --- Application Config & State ---
window.config = {}; 
window.drivers = []; 
window.savedHostConfig = null;
window.savedConfigPanelState = null;

// --- Timers & Intervals ---
window.raceInterval = null;
window.pitInterval = null;
window.liveTimingInterval = null;
window.proxyFetchInterval = null;
window.connectionRetries = 0;
window.MAX_RETRIES = 3;

// --- Constants ---
window.RACE_STATE_KEY = 'strateger_race_state';
window.liveTimingManager = null;
window.syncedTimes = null;

// --- Race Logic State ---
window.state = { 
    isRunning: false, 
    mode: 'normal', 
    trackCondition: 'dry',
    isRain: false, 
    currentDriverIdx: 0, 
    pitCount: 0, 
    startTime: 0, 
    stintStart: 0, 
    pitStart: 0, 
    isInPit: false, 
    fuelStart: 0, 
    stintOffset: 0, 
    activeSquad: 'A', 
    nextDriverIdx: 1, 
    targetStintMs: 0, 
    squadsActive: false,
    pendingPitEntry: false,
    globalStintNumber: 1,
    raceSaved: false,
    stintTargets: [],
    deltaHistory: []
};

// --- Live Timing Configuration ---
window.liveTimingConfig = {
    url: '',
    teamName: '',
    enabled: false,
    demoMode: false
};

window.searchConfig = {
    teamName: '',
    driverName: '',
    kartNumber: ''
};

window.liveData = {
    position: null,
    previousPosition: null,
    lastLap: null,
    bestLap: null,
    laps: null,
    gapToLeader: null,
    competitors: []
};

window.demoState = {
    competitors: [],
    updateInterval: null
};

// --- AI & Strategy Config ---
window.aiStrategyConfig = {
    weatherCondition: 'dry',
    instructions: '',
    starterDriverIdx: 0,
    useAI: false
};

window.cachedStrategy = null;
window.previewData = null;

// ==========================================
// 🌐 INTERNATIONALIZATION (I18N)
// ==========================================
window.currentLang = 'en';

window.translations = {
    en: {
        offline: 'Offline',
        subtitle: 'Endurance Race Strategy Manager',
        host: 'Host',
        hostDesc: 'Manage the race',
        viewer: 'Viewer',
        viewerDesc: 'Watch live',
        yourCode: 'Your Code:',
        retry: 'Retry',
        raceSettings: '⚙️ Race Settings',
        liveTiming: 'Live Timing (Optional)',
        liveTimingUrl: 'Live Timing URL (APEX/RaceFacer)',
        searchBy: 'Search by:',
        team: 'Team',
        kart: 'Kart',
        driver: 'Driver',
        testConnection: 'Test',
        demo: 'Demo',
        manual: 'Manual',
        duration: 'Duration (hours)',
        reqStops: 'Required Stops',
        minStint: 'Min Stint (min)',
        maxStint: 'Max Stint (min)',
        driverLimits: 'Driver Limits (0 = no limit)',
        minDrive: 'Min Drive',
        maxDrive: 'Max Drive',
        pitTime: 'Pit Time (sec)',
        releaseBuffer: 'Release Buffer (sec)',
        doubleStint: 'Double',
        fuel: 'Fuel',
        squads: 'Squads',
        fuelTankTime: 'Fuel Tank Time (min)',
        driversSetup: 'Drivers (mark starter)',
        startRace: 'Start Race (Host)',
        enterCode: 'Enter Host Code:',
        connect: 'Connect',
        disconnect: 'Disconnect',
        code: 'Code:',
        synced: 'Synced',
        simResultPattern: "✅ {stints} stints × ~{avg}min = {totalDrive}min drive\n🏁 Pit stops: {stops} × {pitTime}s = {totalPit}min\n{note}",
        stdStrategy: "Standard strategy - maximize stint length",
        shortStrategy: "Short strategy - minimize stops",
        longStrategy: "Long strategy - save fuel/tires",
        aiStrategyPrefix: "🤖 AI Plan: ",
        raceTime: 'Race Time',
        pitStops: 'Pit Stops',
        dry: 'Dry',
        wet: 'Wet',
        drying: 'Drying',
        targetStint: 'Target Stint',
        buildTime: 'Build Time',
        stintTime: 'Stint Time',
        currentDriver: 'Current Driver',
        activeSquad: 'Active Squad:',
        resting: 'Resting:',
        push: 'Push',
        problem: 'Problem',
        night: 'Night',
        resetMode: '↩️ Reset Mode',
        driverHeader: 'Driver',
        stintsHeader: 'St.',
        totalHeader: 'Total',
        nextDriver: 'Next Driver',
        enterPit: '🏁 Enter Pit',
        inPit: 'IN PIT',
        nextDriverIn: 'Next Driver:',
        refuel: 'Kart Change / Refuel?',
        notifyDriver: 'Notify Driver',
        notified: 'Notified - Waiting for line cross',
        wait: 'Wait...',
        cancelPit: 'Cancel Pit Entry',
        manualInput: 'Manual Input',
        position: 'Position',
        laps: 'Laps',
        lastLap: 'Last Lap',
        bestLap: 'Best Lap',
        gap: 'Gap to Leader',
        inPitNow: 'Currently in Pit',
        apply: 'Apply',
        cancel: 'Cancel',
        waitingData: 'Waiting for data...',
        proxyData: 'Proxy Data:',
        liveView: 'Live View',
        connecting: 'Connecting...',
        connected: 'Connected',
        waitingRace: 'Connected! Waiting for race...',
        disconnected: 'Disconnected',
        enterUrl: '❌ Enter URL',
        enterValue: '❌ Enter',
        testing: '🔄 Testing...',
        found: '✅ Found! Position:',
        notFound: '⚠️ Not found - check details or use iframe',
        error: '❌ Error:',
        confirmEarlyPit: 'Window closed! Enter anyway?',
        confirmExit: '✅ Confirm Line Cross',
        timeExceeded: '🚨 Time Exceeded!',
        problemQuick: '🐢 Problem - Quick Entry!',
        pushExtend: '🔥 Extending! Build time',
        nearLimit: '⚠️ Near limit!',
        targetWindow: '✅ Target Window',
        overExtend: '📥 Over Extended',
        nightActive: '🌙 Night Active',
        pushActive: '🔥 Push Active',
        problemActive: '🐢 Problem Active',
        teamNotFound: 'Team not found',
        connectionIssues: 'Connection issues',
        usingIframe: 'Using iframe',
        connectionFailed: 'Connection failed',
        stopped: 'Stopped',
        racePreview: 'Race Strategy Preview',
        raceStartTime: 'Race Start Time',
        driverSchedule: 'Driver Schedule',
        strategySummary: 'Strategy Summary',
        editStrategy: 'Back to Setup',
        saveStrategy: 'Save Strategy',
        previewStrategy: 'Preview Strategy',
        stopLiveTiming: 'Stop',
        activeRaceFound: 'Active Race Found!',
        raceInProgress: 'A race is currently in progress',
        timeRemaining: 'Time Remaining',
        continueRace: 'Continue Race',
        discardRace: 'Discard & Start New',
        raceWarning: 'Discarding will permanently delete this race data',
        confirmDiscard: 'Are You Sure?',
        confirmDiscardMessage: 'This will permanently delete the active race. This action cannot be undone.',
        yesDiscard: 'Yes, Discard Race',
        noKeepRace: 'No, Keep Race',
        loadStrategy: 'Load Saved Strategy',
        savedStrategies: '📚 Saved Strategies',
        noSavedStrategies: 'No saved strategies yet',
        strategyName: 'Strategy Name:',
        strategySaved: '✅ Strategy saved:',
        aiAssistant: '🤖 AI Strategy Assistant',
        expectedConditions: 'Expected Conditions:',
        mixed: 'Mixed',
        strategyInstructions: 'Strategy Instructions:',
        aiPlaceholder: "e.g., 'Focus double stints during night for Squad A', 'Keep driver X fresh for final stints'...",
        generateAi: '🤖 Generate AI Strategy',
        analyzing: '🤖 Analyzing strategy...',
        aiApplied: '✅ AI strategy applied!',
        aiError: '❌ Error generating strategy',
        pitClosedStart: '🚫 Pit Closed Start (min)',
        pitClosedEnd: '🚫 Pit Closed End (min)',
        finish: 'Finish',
        raceFinished: '🏁 Race Finished!',
        savedToDb: '✅ Strategy saved to database',
        safetyWarning: '⚠️ Safety Warning',
        googleConnect: 'Google Connect',
        signInGoogle: 'Sign in with Google',
        emailTeam: 'Email Team',
        addCalendar: 'Add to Calendar',
        shareStrategy: 'Share Strategy',
        checkAvailability: 'Check Availability',
        recipients: 'Recipients (comma separated)',
        emailSubject: 'Subject',
        message: 'Message',
        attachStrategy: 'Attach current strategy',
        sendEmail: 'Send Email',
        addToCalendar: 'Add to Google Calendar',
        eventTitle: 'Event Title',
        startDate: 'Start Date',
        startTime: 'Start Time',
        location: 'Location',
        inviteDrivers: 'Invite Drivers (emails)',
        addReminder: 'Add reminder (1 day before)',
        createEvent: 'Create Event',
        recipientsHistory: 'Recent recipients found',
        eventsFound: 'Events found on this date:',
        noEvents: 'No events found. You are free!',
        raceStart: 'Race Start',
        raceEnd: 'Race End',
        totalDriving: 'Total Driving',
        avgStint: 'Avg Stint',
        stintCount: 'Stints',
        localhostError: 'AI/DB features require Netlify environment (or netlify dev).',
        loading: 'Loading...',
        strategyLoaded: 'Strategy Loaded!',
        saveSuccess: 'Saved Successfully',
        scheduleTitle: 'Schedule',
        summaryTitle: 'Driver Summary'
    },
    he: {
        offline: 'לא מחובר',
        subtitle: 'מנהל אסטרטגיית מירוצי סיבולת',
        host: 'מארח',
        hostDesc: 'נהל את המירוץ',
        viewer: 'צופה',
        viewerDesc: 'צפה בשידור חי',
        yourCode: 'הקוד שלך:',
        retry: 'נסה שוב',
        raceSettings: '⚙️ הגדרות מירוץ',
        liveTiming: 'Live Timing (אופציונלי)',
        liveTimingUrl: 'קישור Live Timing (APEX/RaceFacer)',
        searchBy: 'חפש לפי:',
        team: 'קבוצה',
        kart: 'קארט',
        driver: 'נהג',
        testConnection: 'בדוק',
        demo: 'דמו',
        manual: 'ידני',
        duration: 'משך (שעות)',
        reqStops: 'עצירות חובה',
        minStint: 'מינ\' סטינט (דק\')',
        maxStint: 'מקס\' סטינט (דק\')',
        driverLimits: 'גבולות נהג (0 = ללא הגבלה)',
        minDrive: 'מינימום נהיגה',
        maxDrive: 'מקסימום נהיגה',
        pitTime: 'זמן פיטס (שניות)',
        releaseBuffer: 'הקדמת התראה (שנ\')',
        doubleStint: 'דאבל',
        fuel: 'דלק',
        squads: 'חוליות',
        fuelTankTime: 'זמן מיכל דלק (דק\')',
        driversSetup: 'הגדרת נהגים (סמן מזנק)',
        startRace: 'התחל מרוץ (מנהל)',
        enterCode: 'הכנס קוד מארח:',
        connect: 'התחבר',
        disconnect: 'התנתק',
        code: 'קוד:',
        synced: 'מסונכרן',
        simResultPattern: "✅ {stints} סטינטים × ~{avg} דק' = {totalDrive} דק' נהיגה\n🏁 עצירות פיט: {stops} × {pitTime} שניות = {totalPit} דק'\n{note}",
        stdStrategy: "אסטרטגיה סטנדרטית - מקסום אורך סטינט",
        shortStrategy: "אסטרטגיה קצרה - מינימום עצירות",
        longStrategy: "אסטרטגיה ארוכה - חיסכון בדלק/צמיגים",
        aiStrategyPrefix: "🤖 תוכנית AI: ",
        raceTime: 'זמן מירוץ',
        pitStops: 'עצירות פיטס',
        dry: 'יבש',
        wet: 'גשם',
        drying: 'מתייבש',
        targetStint: 'יעד סטינט נוכחי',
        buildTime: 'צבור זמן',
        stintTime: 'זמן סטינט',
        currentDriver: 'נהג נוכחי',
        activeSquad: 'חוליה פעילה:',
        resting: 'נחים:',
        push: 'קצב',
        problem: 'תקלה',
        night: 'לילה',
        resetMode: '↩️ איפוס מצב',
        driverHeader: 'נהג',
        stintsHeader: 'סט\'',
        totalHeader: 'סה"כ',
        nextDriver: 'נהג הבא',
        enterPit: '🏁 כניסה לפיטס',
        inPit: 'בפיטס',
        nextDriverIn: 'נהג נכנס:',
        refuel: 'הוחלף קארט / תדלוק?',
        notifyDriver: 'הודע לנהג להתכונן',
        notified: 'הודעה נשלחה - ממתין לחציית קו',
        wait: 'המתן...',
        cancelPit: 'בטל כניסה לפיטס',
        manualInput: 'הזנה ידנית',
        position: 'מיקום',
        laps: 'הקפות',
        lastLap: 'הקפה אחרונה',
        bestLap: 'הקפה הטובה',
        gap: 'פער ממוביל',
        inPitNow: 'כרגע בפיטס',
        apply: 'החל',
        cancel: 'ביטול',
        waitingData: 'ממתין לנתונים...',
        proxyData: 'נתוני פרוקסי:',
        liveView: 'תצוגה חיה',
        connecting: 'מתחבר...',
        connected: 'מחובר',
        waitingRace: 'מחובר! ממתין לתחילת מרוץ...',
        disconnected: 'נותק מהמארח',
        enterUrl: '❌ הכנס קישור',
        enterValue: '❌ הכנס',
        testing: '🔄 בודק...',
        found: '✅ נמצא! מיקום:',
        notFound: '⚠️ לא נמצא - בדוק את הפרטים או השתמש ב-iframe',
        error: '❌ שגיאה:',
        confirmEarlyPit: 'חלון סגור! להיכנס?',
        confirmExit: '✅ אשר חציית קו',
        timeExceeded: '🚨 חריגת זמן!',
        problemQuick: '🐢 תקלה - כניסה מהירה!',
        pushExtend: '🔥 מאריכים! צבור זמן',
        nearLimit: '⚠️ קרוב לגבול!',
        targetWindow: '✅ חלון יעד',
        overExtend: '📥 הארכת יתר',
        nightActive: '🌙 לילה פעיל',
        pushActive: '🔥 קצב פעיל',
        problemActive: '🐢 תקלה פעיל',
        teamNotFound: 'קבוצה לא נמצאה',
        connectionIssues: 'בעיות חיבור',
        usingIframe: 'משתמש ב-iframe',
        connectionFailed: 'החיבור נכשל',
        stopped: 'נעצר',
        racePreview: 'תצוגה מקדימה של אסטרטגיה',
        raceStartTime: 'שעת התחלת המירוץ',
        driverSchedule: 'לוח זמנים נהגים',
        strategySummary: 'סיכום אסטרטגיה',
        editStrategy: 'חזרה למסך ראשי',
        saveStrategy: 'שמור אסטרטגיה',
        previewStrategy: 'תצוגה מקדימה',
        stopLiveTiming: 'עצור',
        activeRaceFound: 'נמצא מירוץ פעיל!',
        raceInProgress: 'מירוץ מתקיים כעת',
        timeRemaining: 'זמן נותר',
        continueRace: 'המשך מירוץ',
        discardRace: 'מחק והתחל חדש',
        raceWarning: 'מחיקה תמחק לצמיתות את נתוני המירוץ',
        confirmDiscard: 'האם אתה בטוח?',
        confirmDiscardMessage: 'פעולה זו תמחק לצמיתות את המירוץ הפעיל. לא ניתן לבטל פעולה זו.',
        yesDiscard: 'כן, מחק מירוץ',
        noKeepRace: 'לא, שמור מירוץ',
        loadStrategy: 'טען אסטרטגיה שמורה',
        savedStrategies: '📚 אסטרטגיות שמורות',
        noSavedStrategies: 'אין אסטרטגיות שמורות עדיין',
        strategyName: 'שם האסטרטגיה:',
        strategySaved: '✅ האסטרטגיה נשמרה:',
        aiAssistant: '🤖 עוזר אסטרטגיה (AI)',
        expectedConditions: 'תנאים צפויים:',
        mixed: 'מעורב',
        strategyInstructions: 'הוראות לאלגוריתם:',
        aiPlaceholder: "לדוגמה: 'תן דאבל סטינטים בלילה לחוליה א', 'שמור את נהג X לסוף'...",
        generateAi: '🤖 צור אסטרטגיה',
        analyzing: '🤖 מנתח אסטרטגיה...',
        aiApplied: '✅ אסטרטגיה הוחלה!',
        aiError: '❌ שגיאה ביצירת אסטרטגיה',
        pitClosedStart: '🚫 פיטס סגור בהתחלה (דק\')',
        pitClosedEnd: '🚫 פיטס סגור בסוף (דק\')',
        finish: 'סיום',
        raceFinished: '🏁 המירוץ הסתיים!',
        savedToDb: '✅ נשמר למסד הנתונים',
        safetyWarning: '⚠️ אזהרת בטיחות',
        googleConnect: 'התחברות Google',
        signInGoogle: 'התחבר עם Google',
        emailTeam: 'שלח מייל לצוות',
        addCalendar: 'הוסף ליומן',
        shareStrategy: 'שתף אסטרטגיה',
        checkAvailability: 'בדוק זמינות',
        recipients: 'נמענים (מופרדים בפסיק)',
        emailSubject: 'נושא',
        message: 'הודעה',
        attachStrategy: 'צרף אסטרטגיה נוכחית',
        sendEmail: 'שלח מייל',
        addToCalendar: 'הוסף ליומן Google',
        eventTitle: 'כותרת אירוע',
        startDate: 'תאריך התחלה',
        startTime: 'שעת התחלה',
        location: 'מיקום',
        inviteDrivers: 'הזמן נהגים (אימיילים)',
        addReminder: 'הוסף תזכורת (יום לפני)',
        createEvent: 'צור אירוע',
        recipientsHistory: 'נמצאו נמענים אחרונים',
        eventsFound: 'אירועים בתאריך זה:',
        noEvents: 'אין אירועים. אתה פנוי!',
        raceStart: 'התחלת מירוץ',
        raceEnd: 'סיום מירוץ',
        totalDriving: 'סה"כ נהיגה',
        avgStint: 'ממוצע סטינט',
        stintCount: 'סטינטים',
        localhostError: 'פיצ\'ר זה עובד רק בשרת (Netlify) ולא מקומית.',
        loading: 'טוען...',
        strategyLoaded: 'אסטרטגיה נטענה בהצלחה!',
        saveSuccess: 'נשמר בהצלחה',
        scheduleTitle: 'לוח זמנים',
        summaryTitle: 'סיכום נהגים'
    },
    fr: {
        offline: 'Hors ligne',
        subtitle: 'Gestionnaire de Stratégie de Course d\'Endurance',
        host: 'Hôte',
        hostDesc: 'Gérer la course',
        viewer: 'Spectateur',
        viewerDesc: 'Regarder en direct',
        yourCode: 'Votre Code:',
        retry: 'Réessayer',
        raceSettings: '⚙️ Paramètres de Course',
        liveTiming: 'Chronométrage en Direct (Optionnel)',
        liveTimingUrl: 'URL Chronométrage (APEX/RaceFacer)',
        searchBy: 'Rechercher par:',
        team: 'Équipe',
        kart: 'Kart',
        driver: 'Pilote',
        testConnection: 'Tester',
        demo: 'Démo',
        manual: 'Manuel',
        duration: 'Durée (heures)',
        reqStops: 'Arrêts Requis',
        minStint: 'Stint Min (min)',
        maxStint: 'Stint Max (min)',
        driverLimits: 'Limites Pilote (0 = illimité)',
        minDrive: 'Min Conduite',
        maxDrive: 'Max Conduite',
        pitTime: 'Temps Pit (sec)',
        releaseBuffer: 'Alerte Avance (sec)',
        doubleStint: 'Double',
        fuel: 'Carburant',
        squads: 'Équipes',
        fuelTankTime: 'Autonomie Réservoir (min)',
        driversSetup: 'Pilotes (marquer le départ)',
        startRace: 'Démarrer Course (Hôte)',
        enterCode: 'Entrer Code Hôte:',
        connect: 'Connecter',
        disconnect: 'Déconnecter',
        code: 'Code:',
        synced: 'Synchronisé',
        simResultPattern: "✅ {stints} relais × ~{avg}min = {totalDrive}min conduite\n🏁 Arrêts: {stops} × {pitTime}s = {totalPit}min\n{note}",
        stdStrategy: "Stratégie standard - maximiser les relais",
        shortStrategy: "Stratégie courte - minimiser les arrêts",
        longStrategy: "Stratégie longue - économiser carburant/pneus",
        raceTime: 'Temps Course',
        pitStops: 'Arrêts Pit',
        dry: 'Sec',
        wet: 'Mouillé',
        drying: 'Séchage',
        targetStint: 'Stint Cible',
        buildTime: 'Accumuler Temps',
        stintTime: 'Temps Stint',
        currentDriver: 'Pilote Actuel',
        activeSquad: 'Équipe Active:',
        resting: 'Au Repos:',
        push: 'Pousser',
        problem: 'Problème',
        night: 'Nuit',
        resetMode: '↩️ Réinitialiser',
        driverHeader: 'Pilote',
        stintsHeader: 'St.',
        totalHeader: 'Total',
        nextDriver: 'Prochain Pilote',
        enterPit: '🏁 Entrer Pit',
        inPit: 'AU PIT',
        nextDriverIn: 'Prochain Pilote:',
        refuel: 'Changement Kart / Ravitaillement?',
        notifyDriver: 'Alerter Pilote',
        notified: 'Alerté - Attente passage ligne',
        wait: 'Attendre...',
        cancelPit: 'Annuler Entrée Pit',
        manualInput: 'Saisie Manuelle',
        position: 'Position',
        laps: 'Tours',
        lastLap: 'Dernier Tour',
        bestLap: 'Meilleur Tour',
        gap: 'Écart au Leader',
        inPitNow: 'Actuellement au Pit',
        apply: 'Appliquer',
        cancel: 'Annuler',
        waitingData: 'En attente de données...',
        proxyData: 'Données Proxy:',
        liveView: 'Vue en Direct',
        connecting: 'Connexion...',
        connected: 'Connecté',
        waitingRace: 'Connecté! En attente de la course...',
        disconnected: 'Déconnecté',
        enterUrl: '❌ Entrer URL',
        enterValue: '❌ Entrer',
        testing: '🔄 Test...',
        found: '✅ Trouvé! Position:',
        notFound: '⚠️ Non trouvé - vérifier ou utiliser iframe',
        error: '❌ Erreur:',
        confirmEarlyPit: 'Fenêtre fermée! Entrer quand même?',
        confirmExit: '✅ Confirmer Passage Ligne',
        timeExceeded: '🚨 Temps Dépassé!',
        problemQuick: '🐢 Problème - Entrée Rapide!',
        pushExtend: '🔥 On prolonge! Accumuler temps',
        nearLimit: '⚠️ Proche limite!',
        targetWindow: '✅ Fenêtre Cible',
        overExtend: '📥 Prolongation Excessive',
        nightActive: '🌙 Nuit Active',
        pushActive: '🔥 Pousser Actif',
        problemActive: '🐢 Problème Actif',
        teamNotFound: 'Équipe non trouvée',
        connectionIssues: 'Problèmes de connexion',
        usingIframe: 'Utilisation de l\'iframe',
        connectionFailed: 'Échec de connexion',
        stopped: 'Arrêté',
        racePreview: 'Aperçu de la Stratégie',
        raceStartTime: 'Heure de Départ',
        driverSchedule: 'Horaire des Pilotes',
        strategySummary: 'Résumé de la Stratégie',
        editStrategy: 'Retour à l\'écran principal',
        saveStrategy: 'Enregistrer la Stratégie',
        previewStrategy: 'Aperçu de la Stratégie',
        stopLiveTiming: 'Arrêter',
        activeRaceFound: 'Course Active Trouvée!',
        raceInProgress: 'Une course est actuellement en cours',
        timeRemaining: 'Temps Restant',
        continueRace: 'Continuer la Course',
        discardRace: 'Supprimer et Recommencer',
        raceWarning: 'La suppression effacera définitivement les données de course',
        confirmDiscard: 'Êtes-vous Sûr?',
        confirmDiscardMessage: 'Cela supprimera définitivement la course active. Cette action ne peut pas être annulée.',
        yesDiscard: 'Oui, Supprimer la Course',
        noKeepRace: 'Non, Garder la Course',
        loadStrategy: 'Charger une Stratégie',
        savedStrategies: '📚 Stratégies Enregistrées',
        noSavedStrategies: 'Aucune stratégie enregistrée',
        strategyName: 'Nom de la stratégie:',
        strategySaved: '✅ Stratégie enregistrée:',
        aiAssistant: '🤖 Assistant Stratégie IA',
        expectedConditions: 'Conditions Prévues:',
        mixed: 'Mixte',
        strategyInstructions: 'Instructions:',
        aiPlaceholder: "ex: 'Double relais la nuit pour l'équipe A', 'Garder pilote X pour la fin'...",
        generateAi: '🤖 Générer Stratégie',
        analyzing: '🤖 Analyse en cours...',
        aiApplied: '✅ Stratégie appliquée!',
        aiError: '❌ Erreur de génération',
        pitClosedStart: '🚫 Pit Fermé Début (min)',
        pitClosedEnd: '🚫 Pit Fermé Fin (min)',
        finish: 'Fin',
        raceFinished: '🏁 Course Terminée!',
        savedToDb: '✅ Enregistré dans la BDD',
        safetyWarning: '⚠️ Avertissement de Sécurité',
        googleConnect: 'Connexion Google',
        signInGoogle: 'Se connecter avec Google',
        emailTeam: 'Envoyer email à l\'équipe',
        addCalendar: 'Ajouter au calendrier',
        shareStrategy: 'Partager la stratégie',
        checkAvailability: 'Vérifier disponibilité',
        recipients: 'Destinataires (séparés par virgule)',
        emailSubject: 'Sujet',
        message: 'Message',
        attachStrategy: 'Joindre la stratégie actuelle',
        sendEmail: 'Envoyer Email',
        addToCalendar: 'Ajouter à Google Agenda',
        eventTitle: 'Titre de l\'événement',
        startDate: 'Date de début',
        startTime: 'Heure de début',
        location: 'Lieu',
        inviteDrivers: 'Inviter pilotes (emails)',
        addReminder: 'Ajouter rappel (1 jour avant)',
        createEvent: 'Créer l\'événement',
        recipientsHistory: 'Destinataires récents',
        eventsFound: 'Événements trouvés :',
        noEvents: 'Aucun événement. Vous êtes libre !',
        raceStart: 'Début de course',
        raceEnd: 'Fin de course',
        totalDriving: 'Temps de conduite total',
        avgStint: 'Stint moyen',
        stintCount: 'Relais',
        localhostError: 'Fonctionnalité serveur (Netlify) requise.',
        loading: 'Chargement...',
        strategyLoaded: 'Stratégie chargée !',
        saveSuccess: 'Enregistré avec succès',
        scheduleTitle: 'Horaire',
        summaryTitle: 'Résumé des pilotes'
    },
    pt: {
        offline: 'Offline',
        subtitle: 'Gestor de Estratégia de Corrida de Endurance',
        host: 'Anfitrião',
        hostDesc: 'Gerir a corrida',
        viewer: 'Espectador',
        viewerDesc: 'Ver ao vivo',
        yourCode: 'Seu Código:',
        retry: 'Tentar Novamente',
        raceSettings: '⚙️ Configurações da Corrida',
        liveTiming: 'Cronometragem ao Vivo (Opcional)',
        liveTimingUrl: 'URL Cronometragem (APEX/RaceFacer)',
        searchBy: 'Pesquisar por:',
        team: 'Equipa',
        kart: 'Kart',
        driver: 'Piloto',
        testConnection: 'Testar',
        demo: 'Demo',
        manual: 'Manual',
        duration: 'Duração (horas)',
        reqStops: 'Paragens Obrigatórias',
        minStint: 'Stint Mín (min)',
        maxStint: 'Stint Máx (min)',
        driverLimits: 'Limites Piloto (0 = ilimitado)',
        minDrive: 'Mín Condução',
        maxDrive: 'Máx Condução',
        pitTime: 'Tempo Pit (seg)',
        releaseBuffer: 'Alerta Antecipado (seg)',
        doubleStint: 'Duplo',
        fuel: 'Combustível',
        squads: 'Equipas',
        fuelTankTime: 'Autonomia Tanque (min)',
        driversSetup: 'Pilotos (marcar partida)',
        startRace: 'Iniciar Corrida (Anfitrião)',
        enterCode: 'Inserir Código Anfitrião:',
        connect: 'Conectar',
        disconnect: 'Desconectar',
        code: 'Código:',
        synced: 'Sincronizado',
        simResultPattern: "✅ {stints} turnos × ~{avg}min = {totalDrive}min condução\n🏁 Paradas: {stops} × {pitTime}s = {totalPit}min\n{note}",
        stdStrategy: "Estratégia padrão - maximizar turnos",
        shortStrategy: "Estratégia curta - minimizar paradas",
        longStrategy: "Estratégia longa - economizar combustível/pneus",
        aiStrategyPrefix: "🤖 AI Plan: ",
        raceTime: 'Tempo Corrida',
        pitStops: 'Paragens Pit',
        dry: 'Seco',
        wet: 'Molhado',
        drying: 'Secando',
        targetStint: 'Stint Alvo',
        buildTime: 'Acumular Tempo',
        stintTime: 'Tempo Stint',
        currentDriver: 'Piloto Atual',
        activeSquad: 'Equipa Ativa:',
        resting: 'Descansando:',
        push: 'Atacar',
        problem: 'Problema',
        night: 'Noite',
        resetMode: '↩️ Reiniciar',
        driverHeader: 'Piloto',
        stintsHeader: 'St.',
        totalHeader: 'Total',
        nextDriver: 'Próximo Piloto',
        enterPit: '🏁 Entrar Pit',
        inPit: 'NO PIT',
        nextDriverIn: 'Próximo Piloto:',
        refuel: 'Troca Kart / Reabastecimento?',
        notifyDriver: 'Alertar Piloto',
        notified: 'Alertado - Aguardando passagem linha',
        wait: 'Aguardar...',
        cancelPit: 'Cancelar Entrada Pit',
        manualInput: 'Entrada Manual',
        position: 'Posição',
        laps: 'Voltas',
        lastLap: 'Última Volta',
        bestLap: 'Melhor Volta',
        gap: 'Diferença ao Líder',
        inPitNow: 'Atualmente no Pit',
        apply: 'Aplicar',
        cancel: 'Cancelar',
        waitingData: 'Aguardando dados...',
        proxyData: 'Dados Proxy:',
        liveView: 'Vista ao Vivo',
        connecting: 'Conectando...',
        connected: 'Conectado',
        waitingRace: 'Conectado! Aguardando corrida...',
        disconnected: 'Desconectado',
        enterUrl: '❌ Inserir URL',
        enterValue: '❌ Inserir',
        testing: '🔄 Testando...',
        found: '✅ Encontrado! Posição:',
        notFound: '⚠️ Não encontrado - verificar ou usar iframe',
        error: '❌ Erro:',
        confirmEarlyPit: 'Janela fechada! Entrar mesmo assim?',
        confirmExit: '✅ Confirmar Passagem Linha',
        timeExceeded: '🚨 Tempo Excedido!',
        problemQuick: '🐢 Problema - Entrada Rápida!',
        pushExtend: '🔥 Prolongando! Acumular tempo',
        nearLimit: '⚠️ Perto do limite!',
        targetWindow: '✅ Janela Alvo',
        overExtend: '📥 Prolongamento Excessivo',
        nightActive: '🌙 Noite Ativa',
        pushActive: '🔥 Atacar Ativo',
        problemActive: '🐢 Problema Ativo',
        teamNotFound: 'Equipa não encontrada',
        connectionIssues: 'Problemas de conexão',
        usingIframe: 'Usando iframe',
        connectionFailed: 'Conexão falhou',
        stopped: 'Parado',
        racePreview: 'Visualização da Estratégia de Corrida',
        raceStartTime: 'Hora de Início da Corrida',
        driverSchedule: 'Horário dos Pilotos',
        strategySummary: 'Resumo da Estratégia',
        editStrategy: 'Voltar para tela principal',
        saveStrategy: 'Salvar Estratégia',
        previewStrategy: 'Visualizar Estratégia',
        stopLiveTiming: 'Parar',
        activeRaceFound: 'Corrida Ativa Encontrada!',
        raceInProgress: 'Uma corrida está atualmente em andamento',
        timeRemaining: 'Tempo Restante',
        continueRace: 'Continuar Corrida',
        discardRace: 'Descartar e Começar Novo',
        raceWarning: 'Descartar irá excluir permanentemente os dados da corrida',
        confirmDiscard: 'Tem Certeza?',
        confirmDiscardMessage: 'Isso excluirá permanentemente a corrida ativa. Esta ação não pode ser desfeita.',
        yesDiscard: 'Sim, Descartar Corrida',
        noKeepRace: 'Não, Manter Corrida',
        loadStrategy: 'Carregar Estratégia',
        savedStrategies: '📚 Estratégias Salvas',
        noSavedStrategies: 'Nenhuma estratégia salva',
        strategyName: 'Nome da Estratégia:',
        strategySaved: '✅ Estratégia salva:',
        aiAssistant: '🤖 Assistente de Estratégia IA',
        expectedConditions: 'Condições Esperadas:',
        mixed: 'Misto',
        strategyInstructions: 'Instruções:',
        aiPlaceholder: "ex: 'Duplo stint à noite para Equipa A', 'Guardar piloto X para o fim'...",
        generateAi: '🤖 Gerar Estratégia',
        analyzing: '🤖 Analisando estratégia...',
        aiApplied: '✅ Estratégia aplicada!',
        aiError: '❌ Erro ao gerar',
        pitClosedStart: '🚫 Pit Fechado Início (min)',
        pitClosedEnd: '🚫 Pit Fechado Fim (min)',
        finish: 'Fim',
        raceFinished: '🏁 Corrida Terminada!',
        savedToDb: '✅ Salvo no banco de dados',
        safetyWarning: '⚠️ Aviso de Segurança',
        googleConnect: 'Conexão Google',
        signInGoogle: 'Entrar com Google',
        emailTeam: 'Enviar e-mail para equipe',
        addCalendar: 'Adicionar à Agenda',
        shareStrategy: 'Compartilhar Estratégia',
        checkAvailability: 'Verificar Disponibilidade',
        recipients: 'Destinatários (separados por vírgula)',
        emailSubject: 'Assunto',
        message: 'Mensagem',
        attachStrategy: 'Anexar estratégia atual',
        sendEmail: 'Enviar E-mail',
        addToCalendar: 'Adicionar ao Google Agenda',
        eventTitle: 'Título do Evento',
        startDate: 'Data de Início',
        startTime: 'Hora de Início',
        location: 'Local',
        inviteDrivers: 'Convidar Pilotos (e-mails)',
        addReminder: 'Adicionar lembrete (1 dia antes)',
        createEvent: 'Criar Evento',
        recipientsHistory: 'Destinatários recentes',
        eventsFound: 'Eventos encontrados:',
        noEvents: 'Nenhum evento. Você está livre!',
        raceStart: 'Início da Corrida',
        raceEnd: 'Fim da Corrida',
        totalDriving: 'Condução Total',
        avgStint: 'Stint Médio',
        stintCount: 'Stints',
        localhostError: 'Recursos do servidor (Netlify) necessários.',
        loading: 'Carregando...',
        strategyLoaded: 'Estratégia carregada!',
        saveSuccess: 'Salvo com sucesso',
        scheduleTitle: 'Horário',
        summaryTitle: 'Resumo dos Pilotos'
    }
};

window.t = function(key) {
    return window.translations[window.currentLang]?.[key] || window.translations['en'][key] || key;
};

window.tFormat = function(key, replacements) {
    let text = window.t(key);
    for (const [placeholder, value] of Object.entries(replacements)) {
        text = text.replace(`{${placeholder}}`, value);
    }
    return text;
};

window.setLanguage = function(lang) {
    if (!['en', 'he', 'fr', 'pt'].includes(lang)) return;
    
    window.currentLang = lang;
    document.documentElement.lang = window.currentLang;
    document.documentElement.dir = window.currentLang === 'he' ? 'rtl' : 'ltr';
    
    const langSelect = document.getElementById('langSelect');
    if(langSelect) langSelect.value = window.currentLang;
    
    window.applyTranslations();
    localStorage.setItem('strateger_lang', lang);
};

window.applyTranslations = function() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
             el.placeholder = window.t(key);
        } else {
             el.innerText = window.t(key);
        }
    });
    
    window.updateSearchPlaceholder();
    const aiInput = document.getElementById('strategyInstructions');
    if (aiInput) {
        aiInput.placeholder = window.t('aiPlaceholder');
    }
};

window.updateSearchPlaceholder = function() {
    const searchType = document.querySelector('input[name="searchType"]:checked')?.value || 'team';
    const input = document.getElementById('searchValue');
    if (!input) return;
    
    const placeholders = {
        en: { team: 'Enter team name', kart: 'Enter kart number', driver: 'Enter driver name' },
        he: { team: 'הכנס שם קבוצה', kart: 'הכנס מספר קארט', driver: 'הכנס שם נהג' },
        fr: { team: 'Nom d\'équipe', kart: 'Numéro de kart', driver: 'Nom du pilote' },
        pt: { team: 'Nome da equipa', kart: 'Número do kart', driver: 'Nome do piloto' }
    };
    
    input.placeholder = placeholders[window.currentLang]?.[searchType] || placeholders.en[searchType];
};